const sentences = [
    "What’s the best fat burning food?",
    "What’s your favorite breakfast?",
    "I always seem to spend hours working out and still don't get results?",
    "How many daily steps do you recommend?",
    "What are your thoughts on low fat products?",
    "Looking to get more toned abs, what do I do?",
    "Is it online coaching you do?",
    "Does creatine work? Should I use it? Is it safe?",
    "Do you help postnatal women?",
    "How can you help me?",
    "Do you provide meal plans?",
    "Can you help with optimizing hormones as we age?",
    "I have no idea where to get started to lose weight. Can you help?",
    "Do you coach men over 30?",
    "Can I do this if I work 9 - 5?",
    "If I have a busy schedule, can I do this?",
    "My brother is a software engineer and spends a lot of time sedentary. Will this program be suitable for him?",
    "Very interesting! My father is looking to help his employees get in shape. Do you offer corporate packages for coaching multiple individuals in a company?", 
    "This looks great. Are you working with clients who have to travel regularly?",
    "How can I get a better pump in the morning?",
    "What’s your opinion on alcohol?",
    "How should I balance my protein intake?",
    "When dieting, is there a limit to how long you should diet before your body shuts down?",
    "When doing Bulgarian split squats, how come some people only use one dumbbell?",
    "I seem to be leaning too far forward when doing squats. Any idea why?",
    "What's the best aid for digestion if I get bloated easily?",
    "I'm getting 8 hours of sleep, and eating correctly, but I'm still feeling lethargic. Any advice?",
    "What are the benefits of exercise by measuring blood pressure?",
    "Why do you eat dark chocolate? Are there any benefits?",
    "Thoughts on nuts & nut butter while in a cutting phase?",
    "Can I have a good diet and gains without supps?",
    "Creatine? Good or Bad?",
    "I’m tempted to get the prestige sleep from prestige labs, what is your opinion?",
    "Best pre and post workout meals?",
    "How long before bed do you get your last meal in?",
    "Is it okay to train a muscle 2 times a week during fat loss?",
    "What is the best chest exercise?",
    "Are there any bad foods to stay away from when your goal is fat loss and build muscle?",
    "Why do you sometimes eat a dinosaur bowl of porridge pre-bed?",
    "Is it bad for me to be in a caloric deficit for too long? (like 500-600 calories of deficit)",
    "Thoughts on taking creatine for a built guy with excess fat?",
    "How do I measure myself to find out my body fat % and lean mass?",
    "How much rest should I have between workouts? Can I workout in the PM and then again in the AM?",
    "How long can one be in a calorie deficit for?",
    "What is the best snack if you are hungry?",
    "Is it okay to do stairmaster cardio (20min) after strength workout?",
    "Should you carb cycle on a lean bulk?",
    "Can I train 2 times a week, Saturday upper body and Sunday Lower body?",
    "Tips for gaining weight?",
    "Why are pro bodybuilders on a low fat diet while on prep?",
    "What are the basic supplements to put on lean mass?",
    "When do you take creatine? And do you take powder or tablets?",
    "Do you have space for any more clients from the US?",
    "Opinion on liquid chalk for grip instead of wrist wraps?",
    "If I eat in a calorie deficit every day but don't go to the gym will I gain fat",
    "60 year old belly fat, best way to shift it?",
    "Do you track your blood sugar level? And if so what's your normal morning reading",
    "Does white bread hinder the process of losing weight?",
    "Is cupping/sports massage beneficial for recovery?",
    "Is the men’s shred a 1 on 1 online coaching program? What does it include",
    "What is your biggest goal right now",
    "Do you have to eat lots of calories to build strength (not size)?",
    "I love bread and pasta but I get very bloated after eating them. What can I do?",
    "When is the best time to do deadlifting? Is it ok to do it with a back and shoulders workout?",
    "Any good HIIT workouts you’d recommend?",
    "On rest days, HIIT or LISS for fat loss? Still trying to bulk",
    "How much does your program cost?",
    "Is it true you can consume too much protein in one sitting? I’ve heard about 40g",
    "Tip to sick abs",
    "My meal plan has 6 meals per day, does it matter if I have 2 of these at the same time ?",
    "Cheat meals! I understand 1 meal per week. Is there a limit as to the size of a meal?",
    "How do you find balance in your diet & training? I feel guilty if I’m not “all in” ",
    "Can tight fascia limit muscle hypertrophy",
    "Thought on EMS training and incorporating it as part of a workout routine",
    "I’m losing weight but I don't see fat loss. How can I improve this?",
    "How much lbs is safe to lose in a week?",
    "I was a leg day skipper and now I need to focus on it to catch up tips!!",
    "What advice would you give to beginners who don't know how to meal prep?",
    "How to start reverse dieting and decrease your daily steps and cardio?",
    "My meal plan has so many vegetables, 2 lbs a week. Do I have to eat that much?",
    "Can I get shredded in 3 months?",
    "What type of workout splits are the most effective for muscle growth?",
    "Can you still get lean while eating sweets?",
    "Do you take glutamine intra workout? And what dose?",
    "Would you recommend anything other than a calorie deficit for fat loss? Got 10-20% to drop",
    "Why do you measure blood sugar to see how your diet is?",
    "Thoughts on fasted vs non fasted training if you train at 5am",
    "Any good podcast recommendations similar to yours?",
    "Thoughts on supplementing fish oil and multivit?",
    "Is it true women take longer to lose weight than men?",
    "Is it possible to lose fat at home and maintain muscle mass?",
    "How do I know if my technique is correct? I’ve watched so many vids but never know if I'm doing the right thing",
    "At 11.9 body fat %- could use a little more work on my abs. How many times a week?",
    "How experienced should one be to take advantage of your program?",
    "Best fat burner supplement?",
    "Do you take pre workout for every training session?",
    "How much is your program for 3 months and 6 months",
    "Best way to stop bloating",
    "Matador diet/regular diet break thoughts. Necessary or waste of time?",
    "Want to lose some tummy fat before vacation in 4 weeks, is just hiit the best or weight & hiit?",
    "Should i take glutamine for muscle recovery?",
    "What does your program include? could I get the info in Spanish",
    "How much time do you spend stretching?",
    "Best condiments for when dieting",
    "Is it possible to lose weight and gain muscle at the same time?",
    "What's the key to keeping on track with your diet and workouts?",
    "Top 3 best gyms in LA",
    "Is coke zero ok to drink?",
    "A good protein powder brand you’d recommend?",
    "Is anterior pelvic tilt fixable? Have back pain during workouts because of it",
    "Upper, lower split or push pull legs or even bro split?",
    "How to increase insulin sensitivity when bulking? Fasting glucose starts to rise a little.",
    "What foods should I eat to naturally increase my testosterone?",
    "Would you use LBM or scale weight for macro calculation as I saw a video and they used LBM",
    "Why do pumps die down mid session?",
    "Best way to loss fat",
    "Can you give a simple explanation of calorie deficit",
    "Best way to avoid shoulder pain when working out? I always retract my scapula as well",
    "Your thoughts on keto",
    "Which is the better workout in the morning or evening?",
    "Do you do intermittent fasting?",
    "Do you use pre workout?",
    "How can we get rid of tennis elbow? Don’t say rest. Not possible",
    "What to do on a rest day to not feel like shit?",
    "Currently doing push pull legs 6 days and one rest day. What do you think?",
    "While lifting heavy, I got a ganglion cyst (synovial cyst) in the wrist. Treatment? Prevention?",
    "What do you think about programs like 75 hard?",
    "Is your nutrition the same on the rest days as on workout days?",
    "Just snapped my Achilles, worried about gaining weight! Ideas for exercises and lose weight",
    "What’s your single top tip for running a successful business?",
    "I got generative Disk Disease. Will I be able to lift heavy? Docs said no squat or deadlifts",
    "Your definition of a dirty bulk. Should people bulk up before getting trim?",
    "Is it bad to “chug” your protein shake vs drinking it slowly?",
    "How do you get rid of water retention?",
    "Thoughts on avocado",
    "Whey protein vs egg white powdered protein",
    "What to do if you feel the biceps or triceps contract more on one side than the other during exercise?",
    "What course would you say someone does to learn to be a fitness instructor?",
    "Should you change your training routine when cutting? Weight/reps etc",
    "DB bench press with feet on bench any good?",
    "I notice you like push pull legs split. Is there something wrong with the typical bro split?",
    "Scale has been up the last 10 days, calories have been low like half usual, should I eat less?",
    "What do you think about low carb diet to lose weight",
    "What split do you recommend for 4 days straight/3 off due to work/family?",
    "Are 6 day workout programs necessary for putting on lean mass in a bulk phase?",
    "Would you recommend some lifting weights daily or to have a few rest days?",
    "Top 3 tips for training delts?",
    "What reps/sets do you do to build muscle?",
    "How you eat and workout on vacation, do you track your food?",
    "Importance of nutrition",
    "Supplements",
    "How much protein should I eat while cutting and bulking?",
    "Can eating bread every day make you gain weight?",
    "Can a healthy diet and structured workout program help reduce snoring?",
    "You said don't use protein, but you use protein powder?",
    "Views on haribos gummy bear 80 grams as post workout during lean bulk (clean bulk)",
    "What apart from weight loss can happen to your body when you don't consume all daily calories etc.",
    "Thought on nootropics for better focus and productivity and general crushing life",
    "What should the macros be for body recomp? (deficit maintenance/surplus)",
    "Your favorite podcast?",
    "An example of daily meals to reach your 500g of carbs",
    "Diet breaks- can they help physically? Thought on when to do it",
    "White rice or brown rice? Why?",
    "Any other podcast you like other than the shredded show",
    "How to carb cycle",
    "Favorite quad focused exercises?",
    "Do you fit your workouts around the rest of your life, your life around your workouts?",
    "Why cuffs over handles on some cable exercises?",
    "How should I take strength training and hypertrophy together?",
    "Best form with low reps or normal form with high reps",
    "What is the average percentage of fat that can be lost per month?",
    "Didn’t train or eat particularly good last week, best tips to get back on track?",
    "I think I’m getting the flu, recommended still go to the gym?",
    "What do you think about evogen supplement e.g lipocide or carnings",
    "Do you lose muscle when exercising on a fasted stomach or the opposite?",
    "How much is a transformation plan? And how long is it?",
    "What are your qualifications?",
    "If you train late at night and have consumed your protein intake, what should you eat post-workout?",
    "Should I stop weights and do more cardio if I wanna shed from 200 to 165",
    "Would you recommend swimming? If so how would you fit this into a program?",
    "What's your favorite sleep tracking app?",
    "How do I make my calves grow?",
    "Is using a massage gun for post workout recovery ok for triceps/biceps?",
    "Pre workout everyday health issues?",
    "Have you seen many people who have stopped working with you and came back",
    "How do you get your coaches?",
    "Is the body Recomp the ideal plan for skinny fat build?",
    "What makes your program different from others? So many choices of coaches out there!",
    "Can I build my body with 55-60 grams of protein a day?",
    "How much rest between workouts?",
    "Best workout split for beginners for maximum results",
    "Thoughts on people including no processed food in their diet?",
    "Who is your dream client?",
    "Can we build muscle while on a calorie deficit?",
    "Advice on turmeric/curcumin for digestion? suggestion s on digestive enzymes?",
    "Why do some people lose weight faster?",
    "Do you work with Vegans at all?",
    "Thoughts on bananas",
    "Do you take pre workouts",
    "7 day to shred possible",
    "How do you adjust your program for people in their 40s+? What type of results can be expected?",
    "It's my first year training, been bulking for 5 months. Should I continue to bulk right now or cut fat?",
    "How long should a diet break last? Been 2 to 3 years of dieting",
    "Cardio before or after the session?",
    "Are all calories created equal to consuming fat but staying in deficit would help me lose weight?",
    "Any tips for dealing with tricep tendonitis",
    "Clenbuterol for weight loss ok?",
    "What do you think about half half reps see all these youtubers going on about half reps to help you grow",
    "I'm 40 and diabetic started gym just 2 months back found very slow progress, I wanna know more",
    "How many times a week do you do cardio?",
    "Can we eat a whole 12 eggs per day?",
    "While on a calorie deficit can we eat maintenance calories for one day?",
    "Is it harder to lose weight as you get older?",
    "206 lbs 5’11’’ 19% bf waist #5 166 lbs lean muscle. How long does it take to get to 10 % bf?",
    "What advice/do you recommend for skinny guys with weights?",
    "Do you use journals?",
    "Your best bench press?",
    "Does drinking more water make you look less defined or more defined?",
    "What is your daily food?",
    "Why do coaches make their clients shredded before a gaining phase and does it apply to everyone?",
    "Which is the best time to hit the gym, morning or evening?",
    "stim free pre workout thoughts?",
    "Haven’t pulled 400s for over a year. Think I could pull it again soon?",
    "When is best to weigh food(meat,vegetable) row or cooked?",
    "Is it okay after 6 months of cutting to go bulk with increasing cals 200 every 10 days to avoid fat?",
    "Protein shakes pre or post workout?",
    "Can you train for an iron man and put on muscle?",
    "How much is your fitness program?",
    "Is it better to work out one muscle group a day or two?",
    "How many different types of workout do you do per muscle?",
    "I’m 165 but still quite skinny fat. Should I cut or bulk?",
    "Thoughts on bikram yoga and lifting routine? Active rest day activity?",
    "Are preacher curls as effective as cable curls?",
    "Any remedies for calluses",
    "Best teas to ease digestion?",
    "What is the best way to start transformation? What form should I start?",
    "More calorie deficit the more you lose weight?",
    "On one clean bulk how do you know when it’s right to up your calorie intake?",
    "What do you do on rest days?",
    "I have suddenly had a massive decrease in appetite. What should I do to actually enjoy eating?",
    "Best way to lose a beer belly and man boobs? Any workouts in particular?",
    "Tips for hard gainer?",
    "My BMI is low, but my body fat ratio is high. Step to become shredded from here?",
    "Outside elbow pain. What may be causing this during training?",
    "When is the best exercise for triceps to get rid of bingo wings?",
    "Does sleeping after midnight but still getting 7-8 hours of sleep impact muscle gain?",
    "I have 16% body fat. Should I bulk or cut first?",
    "Do you recommend training each muscle group more than once a week?",
    "Tips for bodybuilding with hyper mobility",
    "Are you step on top morning cardio?",
    "How long should you give a muscle group to recover?",
    "What does fitness mean to you?",
    "How do i keep motivated? stuck at the same weight",
    "Why are you so handsome?",
    "Do you do workouts designed for women?",
    "Which whey protein do you recommend?",
    "Your age? Bro",
    "What makes you stand out as a coach and which parts of your physique need more attention?",
    "How long does the session go for in your programs?",
    "How do i get more information on your work programs",
    "What would you do differently if starting a business again?",
    "What is the best way to work the legs when there isn’t much equipment that you can use?",
    "How do you think a person come out of a “depression” (some advice)",
    "Always motivate me, thanks",
    "How do you get motivated in the gym",
    "Are you also a coach outside of LA? Around the states?",
    "How often do you stretch?",
    "Should I include drop sets in my workout?",
    "Any suggestions on recovery?",
    "What do you think about protein gainer serious Mass for real?",
    "Where are you from?",
    "Why does it just take so long to gain weight but so short to lose your progress?",
    "Do you do intermittent fasting or have you ever done it before? What's your take on that?",
    "Cardio after drinking alcohol to wash it away",
    "Favorite football team?",
    "Is it hard for you to train everyday and have this discipline to yourself everyday?",
    "Do you speak Spanish?",
    "Good thing or bad to feel discomfort inside a muscle when we work 1 or 2 days after a training session?",
    "How long do you sleep during a day and how much is important in reaching your goal?",
    "Rest days. How important is it? Do you take them?",
    "Can you cut and put muscle on at the same time? I don't want to get bigger but don't want to lose gains",
    "Other ways of getting my fat in during the day apart from avocado and nuts?",
    "Would you do a 12 or 16 week program to get lean?",
    "Best way of gain muscle",
    "What qualification would you look for in PT?",
    "Do you have 6 month programs only?",
    "What is your biggest achievement this year?",
    "Also what's your favorite form of cardio when you're cutting ?",
    "Do you do cardio?",
    "What do you think of powerlifting shoes for quads?",
    "Why don't you want to open up your own gym?",
    "Which pre workout would you recommend? One that doesn't make you giddy for hours after",
    "Do you have only weight loss programs? Or a muscle gain program as well?",
    "Is this correct to take a pre workout and also an intra workout? I've been feeling a bit jittery doing both.",
    "How many times have you been training today, dude?",
    "I can’t lose weight",
    "During a cheat meal, should we remain reasonable?",
    "Is it okay to workout everyday?",
    "Do you cardio when you bulk at all?",
    "Do you do 2 biceps exercises in a workout?",
    "How many times a week do you weight train?",
    "Why are you not doing fitness full time yet?",
    "What is the best tip for cardio workouts?",
    "Wanna build muscle, sitting at 24/25% bf… surplus/cut or maintain calories",
    "Why is cereal so important after a session?",
    "push/pull/legs,upper/lower or classic bodybuilding split for natural lifters?",
    "Would you recommend a low volume high intensity style of training when the main goal is weight loss?",
    "What plan should I be doing If i'm really busy?",
    "I can still barely walk after the first leg session in a long time but I am meant to train them tonight. What should I do ?",
    "Exercise to target/isolate the bottom portion of the chest",
    "Any favorite cheat meal?",
    "Can you lose fat and build muscles in your first and second year of training?",
    "When are you doing another round of discounts?",
    "Hey Dylan, should I eat cereal without milk after workout if the gym’s far?",
    "When you're back at Golds for the proper catch up?",
    "I've never seen such good result since I started your 12 week plan",
    "How many gym sessions per week are required with your program",
    "Have you thought about visiting Canada, I’m Canadian btw and love your work",
    "When would I recommend eating a protein bar in the morning or pre workout or after work?",
    "I'm trying my first bulk.How should I bulk and is there a limit to how much the protein powder to take?",
    "I love what you do. Do you recommend creatine?",
    "Notice you only do 2 sets for some exercises, is that so you can cover more variation",
    "What's the most important thing when looking to lose weight/tone up?",
    "Best tips for people in teen years/ new to lifting",
    "Body part split/legs push pull for lean mass",
    "What is going through your mind right before a lift?",
    "Hi Dylan!! Tips for legs growth?",
    "Sorry if i'm being rude to ask what your age?",
    "Any spots left for 12 week program?",
    "Do you eat carb at all on rest day?",
    "Thoughts on competing, worth it all?",
    "Bro would you recommend just solid sets with progressive lifts? Or add in drop sets, supper sets?",
    "What % protein carb fats should you use on lean bulk?",
    "Any advice for a guy who’s skinny but has a sort of rounded stomach?",
    "Best time for creatine and bcaa",
    "In small surplus at mo can you bulk if not when is it right to increase the surplus",
    "Most effective diet you’ve seen get results?",
    "Should you pull the bar towards you during an RDL or should you just let the bar hang?",
    "When you go on vacation do you track your food?",
    "What’s the optimal mix of cardio and weight training for sustainable physique gains?",
    "Do you suggest full body workouts? If so, how often and how many rest day?",
    "How to fit skinny fat should we eat surplus, maintenance or deficit?",
    "Walking lunges or bulgarian split squats?",
    "Are your clients doing a lot of cardio?",
    "Are you a believer",
    "Are there foods to stay away from or just better ways to prepare them?",
    "Do you use any sweeteners for your coffee?",
    "Is training body part once a week enough to gain muscle(push pull leg)",
    "How to start to get into shape with a minor neck injury cause pain when you workout?",
    "Do you play sports? Favorite sport?",
    "Advice to short people to lose fat who need to be on a much lower calorie intake",
    "How can I start your program with you? Is it only weight loss or can you do mass gain?",
    "Whats the best way of reducing fat continuously?",
    "Is doing keto diet a good way to reduce fat from the body?",
    "Whats your body fat percentage?",
    "Is your coaching program suited to someone living in NYC?",
    "Thought on using clenbuterol?",
    "On maintenance calories can you burn the little excess fat you carry and add any muscle?",
    "Does strength training cause you to bulk rather than cut if you’re trying to lose weight?",
    "Tips for gynaecomastia",
    "Best workout split?",
    "What are the top 3 reason why someone doesn’t get result in gym?",
    "How many transformations are you responsible for?",
    "Is it bad to train fasted?",
    "How do you like the vivo barefoots. Do you use for legs training?",
    "I notice you don’t do pull ups on your videos. Do you not rate them as an exercise?",
    "Your favorite food and body builder and exe.",
    "If you don’t allow yourself a cheat meal will you lose weight slower than if you dis have one?",
    "TD surplus 500kcal weight staying the same after 3w can i still bulk?",
    "Is a carb surplus more important than calories surpluses for bulking?",
    "Can bulk effective on keto?",
    "Really not feeling well this week, will a week of rest from the gym hurt me massively?",
    "How do you charge? A set monthly amount by direct debit, or set amount upfront?",
    "What micro split do you recommend for cutting? And bulking?",
    "How do you overcome body dysmorphic disorder?",
    "What the best way to lose belly fat",
    "How much is the metabolic af program?",
    "Do your plans cost money?",
    "Is intermittent fasting a good approach to reduce fat while building muscle?",
    "Can I still get ripped at 47 years old?",
    "Citrulline malate, what do you think about it?",
    "Help for a girl with PCOs whos struggling to lose weight- even with staying in 350cal deficit",
    "Does protein source matter much?calories inside e.g 20g whey or 20g from 400ml milk?",
    "Lower back pain after squat what to do?",
    "In 5g of creatine really ideal for everyone? Does a bigger person need more? Like 10g?",
    "How to get perfect shoulders at home with 2 dumbbells",
    "What a body fat should a woman be if shes 5’8 height?",
    "Taking more than 2 scoops of protein a day is bad or ok?",
    "I can’t lose weight. I always seem to fail. Any tips?",
    "Best way to burn fat?- 500 daily intake 4x week exercise, and some cardio burn almost no lbs",
    "Want to be part of your transformation asap",
    "Hey can we start transformation with you without booking any call from you guys?",
    "Favorite protein while cutting",
    "Current pt says Im still lean whilst bulk and just water? AM I being para or is that a thing?",
    "Im struggling with deficit die to a sweet tooth any suggestions?",
    "You guys have a clear cut plan for everyone how do you do that and do you have clients from Europe?",
    "How the best measure of your waist?",
    "Working with you is another 15 months from march, can’t wait",
    "Having a stomach issue with all food try to take food out but no difference",
    "I do morning fasted workout, what's a good time to start eating on the rest of the days?",
    "When taking a big inhale in through diaphragm to brace before squat is this to be done?",
    "Running is the best or weight training for fast fat loss",
    "Start the program next month post surgical  recovery, cannot wait!!",
    "Can i take creatine in morning empty stomach",
    "Is it actually possible to reach 0% body fat even if it's unhealthy?",
    "How much is your  black  Friday deal?",
    "If you get a training program. In addition, How much is the cost for the food per month (roughly)?",
    "I’m in Hawaii. What would a 3 month training session and plan cost me?",
    "Any free diet and workout plan for fat loss?",
    "I do a 15 minute cardio warmup before I workout it's this detrimental to my work session?",
    "First photoshoot tomorrow at 12pm. Any nutritional tips? Avoid this? Thanks.",
    "Do you recommend fasted morning workouts?",
    "I have strained and torn my lat on the right. What's the best way to recover and how long to heal?",
    "I can’t grow my legs no matter how hard I try. Train them twice a week",
    "If I train 3 times a week using only bodyweight, will I get lean or just skinny?",
    "How do you get better at pullups? I can barely do 1( Currently 145 lbs)",
    "Exercise suggestions to get legs to build on the outside? I seem to only see shape on the inner thigh",
    "Your opinion about Phosphatidic Acid?",
    "Can I get the same results training x3 weeks x4 times if I train hard?",
    "I’m a big guy, have a good amount of muscle, but body fat I’m cutting should I go light/more reps?",
    "Training for 12 years. Very little time to workout now. 2/week and max 3. Should I do full body",
    "Energy? Eating right and exercising but I’m wiped out.",
    "Thoughts on only consuming carbs pre and post workout meals?",
    "Haven’t had a cheat meal in 4 years. Is it something I should consider?",
    "I get digestive problem when eating and flying as well, is there a reason for this?",
    "Best audio books for self discipline/mindset?",
    "How many calories should be consumed as a pre workout meal? & recommended macros",
    "Do you do customize meal plans or just give macro target",
    "How often do you fast",
    "Is getting enough sleep essential to muscle building? How much is enough for an average 20 year old ?",
    "What’s the best glute workout",
    "During workouts, do you recommend progressive overload or weight that is challenging?",
    "Is starting at age 27 to get huge too late?",
    "Best way to lose belly fat",
    "How to stop binge eating on a calorie deficit?",
    "So you can loose body fat of just eating mc donalds but in a deficit?",
    "Got pins and needles in my thumb when squatting? Any reason for this still feel I coup",
    "Following on a previous question about rest between sets, What’s the typical amount of wait time, 1 min?",
    "Love your page btw. Are any of your plans suitable for vegetarians or vegans at all?",
    "Do you lower calories on rest days for clients?",
    "Pull up- how many reps are we looking for with a band till we can use a lighter one?",
    "Gym recommendation in Utah",
    "Finished atomic habits, what else do you recommend?",
    "Do you think 1 on 1 personal training is decreasing?",
    "Should you still consume a large portion of daily carbs before workout when bulking?",
    "I’m about 285 on a cut so should I eat 280g of protein a day",
    "How can I get rid of man boobs fats or more effectively? Struggled for years with them",
    "What does your service typically cost?",
    "I train 7 days a week, 2 hours per day, is it too much?",
    "What do you think the best dumbbell exercise for legs?",
    "For cycling what’s a healthy ratio for carbs? E.g 50g low 200g high? Also what are you must have sups?",
    "How often do you train over Xmas? I’m annoyed I always miss 4-5 days in 2 weeks",
    "Blending whey protein oats water in the blender to have str8 after workout does it affect the whey negatively?",
    "Thought on lifting straps",
    "What do you recommend for abdominal exercise?",
    "Should you take creatine when cutting?",
    "Can you gain muscle and get ripped at 36?",
    "Guide me about lean our body for 12 months",
    "Your thoughts on the new supplements needs- thyroid stack?",
    "Menopause has kicked my butt any suggestions to help lose?",
    "Is it normal to implement fasting on non-training days?",
    "If I work graveyard will the training be the same or will it change",
    "Supplements and Acne thoughts?",
    "Do you think bodyweight workouts are effective at building muscle? I’m waiting on new weights",
    "Should I counting trace protein in my macro?",
    "Positive for COVID, is it better to pause training and rest or still do the best I can in quarantine",
    "What are your plans for your birthday?",
    "What’s the best way to track if counting macros is only 30% accurate",
    "Is it okay to do weight training in the morning and intense cardio in the evening for fat loss? Any advice?",
    "Should the torso still be parallel to the floor with an underhand barbell row?",
    "How do you stay motivated every day other than 'I love what I do'? Lol",
    "Best app to log/record training reps?(to track progress)",
    "How many grams of protein can be consumed in one hit. Is there a gap between. Thanks",
    "Why does someone need to get shredded first before bulking? Why can’t big boy get bigger before shred",
    "What do you think about trt?",
    "What is the price to work with you?",
    "What do you think about intermittent fasting? GSP the MMA fighter swears by it",
    "What is the best time to get trained? morning /Evenings?",
    "Do you have to hit the muscle 2 a week build muscle? Ex 2 full triceps workouts",
    "Thought on sarms?",
    "Have an injury can’t train how long take to lose strength?",
    "Once abs are visible, you get in cal surplus to build muscle. How much weight will you gain?",
    "Do legs exercise really help you grow the upper body",
    "Do you train on Christmas Day & boxing Day?",
    "I am in Colombia. Can I purchase your training Plan?",
    "How long do you map each session for in the gym? Over an hour?",
    "Thoughts on super setting after your compound movement to maximize time and tension?",
    "I’m in 286 mainly fat should I also do ab exercises to strengthen core or only when I’m down to 10% BF",
    "Can I start bulking immediately after finishing cutting?",
    "Are deadlifts essential for a good program?",
    "Thanks for educating! Is it normal for men to go bald with training?",
    "Was/Is there any clients you were not able to transform?",
    "Have you ever had plastic surgery or jaw surgery?",
    "Do you use anything like an Iwatch or whoop to track your workout?",
    "If you had one for exercise, would you choose the bar or the dumbbell?",
    "Optimum time to have protein post-workout",
    "If this wasn’t your job. What would you do for a living",
    "How to gain weight with a fast metabolism please see DM",
    "What's an optimal macro split for muscle building",
    "What is the best time to do cardio? Before lift weights or after lift weights?",
    "How to grow in the fitness industry any tips?",
    "Abs visible, going to start cal surplus diet. Best carbs to add to build muscle effectively?",
    "What's your opinion of mixing Keto diet with intermittent fasting?",
    "Can you build legs without barbell squats?",
    "What is the average time spent in the gym on a single session. e.g., Push/pull/legs",
    "Can creatine cause higher heart rate/anxiety?",
    "Wrists always let me down in heavier lifts/they get strained easy. Any tips/advice?",
    "Is creatine monohydrate and Pre Workout the same thing?",
    "How do you make 20k steps in a day?",
    "Is it okay to do a PM workout then an AM push workout the next morning?",
    "Should we incorporate cheese and other dairy products into our diet? Currently in cyclic carbs",
    "Is the stepper bad for your joints?",
    "Do you think people who are thin but don’t workout are that way out of luck or are they trying",
    "Is it normal to get motivated someday and then lose motivation when you at the gym",
    "What’s the best form of weight loss if you work 6 days a week and can’t eat enough?",
    "Wrist supports?",
    "Do you recommend a belt with deads and squats? Or just stick to the straps?",
    "What would be a good split for higher vol as my body seems to react better to that low vol.",
    "34 years. 5’11. 240. What’s a good target weight to aim for by the end of the year?",
    "I’ll be 46 in July. 6’4’’ 265 lbs with 176 of muscle mass. How far should I cut before bulking?",
    "How to track daily macros for a family man when daily dinners are different and not prepared by me.",
    "Do you have a video/ link on warm up/cool down and stretching routines?",
    "Lever belts vs prong belts? Which do you suggest?",
    "Any advice on the use of pre workout during a cut/shred?",
    "I see nutritionists post about intuitive eating- seems like a load of crap. Thoughts?",
    "Have you ever visited Europe?",
    "Do you recommend cardio when bulking? Or is hitting a step count fine?",
    "Carb cycle video. Loading through your day, is that to train at night? I am confused",
    "Can you help if I have no motivation?",
    "Finish all calories at dinner time or have some left for a snack in the evenings? Which is better?",
    "Massage gun help with shoulder tendonitis?",
    "I feel like no matter how hard I train or eat- I can’t fully dial in the level I want- I need help",
    "What’s the best diet for a low body fat percentage?",
    "What’s the best program for cutting? Looking for a program for a home gym as just in lockdown",
    "What’s the difference/ benefits to floor dumbbell press?",
    "Should training be any different for very tall guys?",
    "Hi, should I do chest/biceps or chest/triceps on the same day?",
    "How can I get toned much quicker or get better results in less time?",
    "Can your body only digest 30g of protein at a time?",
    "How do I find your podcast?",
    "So protein intake the same for shredding or bulking?",
    "Is it bad to always squat with heels elevated?",
    "Hi, how long should a female bulk for before a mini cut?",
    "Would/do you train people from other states & what is your approach to online coaching?",
    "Is a cooling down always necessary?",
    "Can you build muscle if you eat enough protein while in a calorie deficit?",
    "Thought on BFR training",
    "Do you recommend mass gainers for bulking up especially hard gainers?",
    "What books are you reading currently?",
    "If you’re on holiday for 4 days and can’t control what you eat or workout will you lose progress?",
    "Suggestions for bigger forearms",
    "Your recommendations on immunity boosters?",
    "What can eating late do to your body if you're doing intermittent fasting? Example Says 2 pm until 10",
    "How many calories should a person consume a day? E.g with a deficit how many should be left?",
    "Does creatine cause stomach upset and bowel irritation?",
    "Any benefit to big hoodies & sweatpants when training? Some bodybuilders do it",
    "Do you recommend taking fish oil?",
    "Hey Dylan, is Vit D necessary if you live in California? Where we have lots of sunlight",
    "Do you take in coaching French guys?",
    "As a beginner is it true you can burn fat and build muscle?",
    "Lagging delts",
    "Creatine tablets or powder? Any difference?",
    "Is there any difference between lateral raises and delta raises or the same thing?",
    "Do you do thrusts to build good glutes?",
    "Going “off plan” with nutrition for 1 meal, do you compensate/restrict? Or back on track",
    "Best pre-workout meal if you train first thing in the morning, 5 am?",
    "Thought on the nutritional value of almonds. Walnuts and Brazilian nuts?",
    "I need to stay focused on training but with closed gyms it is difficult. What do you suggest?",
    "If I deficit 500kcal a day does that mean I can have a free meal of 3500 kcal on the 6th day or 7th?",
    "Thoughts on using fasting as a way to achieve a calorie deficit?",
    "How long do you walk for in the morning? Do you listen to podcasts or music?",
    "Your personal trainer. Do you train with people online as well?",
    "Can you lose weight and gain muscle at the same time or do you have to lean bulk and then cut?",
    "Does creatine harm your kidney or liver? In a long time taking",
    "What type of exercise can I do to build muscle if I have acid reflux",
    "Crazy mood swings and bad digestion in the first few days after cutting carbs- normal?",
    "Do you have any advice to control late-night eating?",
    "I’m starting men’s shred on Monday. What top 3 tips can you give me please?",
    "What do I do with shin/tibia pains after jogging?",
    "Thoughts on huel?",
    "Reducing inflammation may help get better results? On which %?",
    "Can you get results without equipment at home workout?",
    "Can we build muscle during a calorie deficit?",
    "Are rest days needed? I do a 4-day split and repeat and don’t feel I need an extra day of rest",
    "Would you get 1g per lb of protein from complete sources and not count trace towards it?",
    "Any difference in taking creatine hcl or monohydrate when cutting?",
    "Can your program be completed at home with no access to weights?",
    "Do you need to spread your protein intake throughout the day for synthesis?",
    "Can you take creatine while leaning out/fat loss?",
    "Best exercise in your opinion to target the upper chest",
    "Would it be detrimental having your gym session first thing in the morning, fasted?",
    "You said early morning fasted training isn’t an optimal time. What would you say is optimal?",
    "Do we need to account for greens powder calories?",
    "Good meals for a packed lunch for work, please",
    "What books do you recommend for a strong mindset/ building good habits and discipline?",
    "What is your biggest fear that you had to overcome?",
    "I’m strong muscular but fat. What to do?",
    "What is the best exercise for the lower part of the chest?",
    "What is the reason for uneven abs?",
    "Any experience with Herbalife products?",
    
];

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

function generateSentences() {
    const quantitySentences = document.getElementById('quantitySentences').value;
    const resultContainer = document.getElementById('result');

    // Clonar el array de oraciones para no alterar el original
    const sentencesCopied = sentences.slice(0);

    // Barajar las oraciones para obtener un orden aleatorio
    shuffleArray(sentencesCopied);

    // Tomar la cantidad de oraciones solicitadas
    const sentencesSelected = sentencesCopied.slice(0, quantitySentences);

    // Mostrar las oraciones en el contenedor
    resultContainer.innerHTML = sentencesSelected.join('<br>');
}

function copySentences() {
    const resultContainer = document.getElementById('result');
    const sentencesText = resultContainer.innerText.trim();

    const textarea = document.createElement('textarea');
    textarea.value = sentencesText;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);

   // alert('Sentences copied to the clipboard.');
}
