const questions = [
    "What’s the best fat burning food?",
    "What’s your favorite breakfast?",
    "I always seem to spend hours working out and still don't get results?",
    "How many daily steps do you recommend?",
    "What are your thoughts on low fat products?",
    "Looking to get more toned abs, what do I do?",
    "Is it online coaching you do?",
    "Does creatine work? Should I use it? Is it safe?",
    "Do you help postnatal women?",
    "How can you help me?",
    "Do you provide meal plans?",
    "Can you help with optimizing hormones as we age?",
    "I have no idea where to get started to lose weight. Can you help?",
    "Do you coach men over 30?",
    "Can I do this if I work 9 - 5?",
    "If I have a busy schedule, can I do this?",
    "My brother is a software engineer and spends a lot of time sedentary. Will this program be suitable for him?",
    "Very interesting! My father is looking to help his employees get in shape. Do you offer corporate packages for coaching multiple individuals in a company?", 
    "This looks great. Are you working with clients who have to travel regularly?",
    "How can I get a better pump in the morning?",
    "What’s your opinion on alcohol?",
    "How should I balance my protein intake?",
    "When dieting, is there a limit to how long you should diet before your body shuts down?",
    "When doing Bulgarian split squats, how come some people only use one dumbbell?",
    "I seem to be leaning too far forward when doing squats. Any idea why?",
    "What's the best aid for digestion if I get bloated easily?",
    "I'm getting 8 hours of sleep, and eating correctly, but I'm still feeling lethargic. Any advice?",
    "What are the benefits of exercise by measuring blood pressure?",
    "Why do you eat dark chocolate? Are there any benefits?",
    "Thoughts on nuts & nut butter while in a cutting phase?",
    "Can I have a good diet and gains without supps?",
    "Creatine? Good or Bad?",
    "I’m tempted to get the prestige sleep from prestige labs, what is your opinion?",
    "Best pre and post workout meals?",
    "How long before bed do you get your last meal in?",
    "Is it okay to train a muscle 2 times a week during fat loss?",
    "What is the best chest exercise?",
    "Are there any bad foods to stay away from when your goal is fat loss and build muscle?",
    "Why do you sometimes eat a dinosaur bowl of porridge pre-bed?",
    "Is it bad for me to be in a caloric deficit for too long? (like 500-600 calories of deficit)",
    "Thoughts on taking creatine for a built guy with excess fat?",
    "How do I measure myself to find out my body fat % and lean mass?",
    "How much rest should I have between workouts? Can I workout in the PM and then again in the AM?",
    "How long can one be in a calorie deficit for?",
    "What is the best snack if you are hungry?",
    "Is it okay to do stairmaster cardio (20min) after strength workout?",
    "Should you carb cycle on a lean bulk?",
    "Can I train 2 times a week, Saturday upper body and Sunday Lower body?",
    "Tips for gaining weight?",
    "Why are pro bodybuilders on a low fat diet while on prep?",
    "What are the basic supplements to put on lean mass?",
    "When do you take creatine? And do you take powder or tablets?",
    "Do you have space for any more clients from the US?",
    "Opinion on liquid chalk for grip instead of wrist wraps?",
    "If I eat in a calorie deficit every day but don't go to the gym will I gain fat",
    "60 year old belly fat, best way to shift it?",
    "Do you track your blood sugar level? And if so what's your normal morning reading",
    "Does white bread hinder the process of losing weight?",
    "Is cupping/sports massage beneficial for recovery?",
    "Is the men’s shred a 1 on 1 online coaching program? What does it include",
    "What is your biggest goal right now",
    "Do you have to eat lots of calories to build strength (not size)?",
    "I love bread and pasta but I get very bloated after eating them. What can I do?",
    "When is the best time to do deadlifting? Is it ok to do it with a back and shoulders workout?",
    "Any good HIIT workouts you’d recommend?",
    "On rest days, HIIT or LISS for fat loss? Still trying to bulk",
    "How much does your program cost?",
    "Is it true you can consume too much protein in one sitting? I’ve heard about 40g",
    "Tip to sick abs",
    "My meal plan has 6 meals per day, does it matter if I have 2 of these at the same time ?",
    "Cheat meals! I understand 1 meal per week. Is there a limit as to the size of a meal?",
    "How do you find balance in your diet & training? I feel guilty if I’m not “all in” ",
    "Can tight fascia limit muscle hypertrophy",
    "Thought on EMS training and incorporating it as part of a workout routine",
    "I’m losing weight but I don't see fat loss. How can I improve this?",
    "How much lbs is safe to lose in a week?",
    "I was a leg day skipper and now I need to focus on it to catch up tips!!",
    "What advice would you give to beginners who don't know how to meal prep?",
    "How to start reverse dieting and decrease your daily steps and cardio?",
    "My meal plan has so many vegetables, 2 lbs a week. Do I have to eat that much?",
    "Can I get shredded in 3 months?",
    "What type of workout splits are the most effective for muscle growth?",
    "Can you still get lean while eating sweets?",
    "Do you take glutamine intra workout? And what dose?",
    "Would you recommend anything other than a calorie deficit for fat loss? Got 10-20% to drop",
    "Why do you measure blood sugar to see how your diet is?",
    "Thoughts on fasted vs non fasted training if you train at 5am",
    "Any good podcast recommendations similar to yours?",
    "Thoughts on supplementing fish oil and multivit?",
    "Is it true women take longer to lose weight than men?",
    "Is it possible to lose fat at home and maintain muscle mass?",
    "How do I know if my technique is correct? I’ve watched so many vids but never know if I'm doing the right thing",
    "At 11.9 body fat %- could use a little more work on my abs. How many times a week?",
    "How experienced should one be to take advantage of your program?",
    "Best fat burner supplement?",
    "Do you take pre workout for every training session?",
    "How much is your program for 3 months and 6 months",
    "Best way to stop bloating",
    "Matador diet/regular diet break thoughts. Necessary or waste of time?",
    "Want to lose some tummy fat before vacation in 4 weeks, is just hiit the best or weight & hiit?",
    "Should i take glutamine for muscle recovery?",
    "What does your program include? could I get the info in Spanish",
    "How much time do you spend stretching?",
    "Best condiments for when dieting",
    "Is it possible to lose weight and gain muscle at the same time?",
    "What's the key to keeping on track with your diet and workouts?",
    "Top 3 best gyms in LA",
    "Is coke zero ok to drink?",
    "A good protein powder brand you’d recommend?",
    "Is anterior pelvic tilt fixable? Have back pain during workouts because of it",
    "Upper, lower split or push pull legs or even bro split?",
    "How to increase insulin sensitivity when bulking? Fasting glucose starts to rise a little.",
    "What foods should I eat to naturally increase my testosterone?",
    "Would you use LBM or scale weight for macro calculation as I saw a video and they used LBM",
    "Why do pumps die down mid session?",
    "Best way to loss fat",
    "Can you give a simple explanation of calorie deficit",
    "Best way to avoid shoulder pain when working out? I always retract my scapula as well",
    "Your thoughts on keto",
    "Which is the better workout in the morning or evening?",
    "Do you do intermittent fasting?",
    "Do you use pre workout?",
    "How can we get rid of tennis elbow? Don’t say rest. Not possible",
    "What to do on a rest day to not feel like shit?",
    "Currently doing push pull legs 6 days and one rest day. What do you think?",
    "While lifting heavy, I got a ganglion cyst (synovial cyst) in the wrist. Treatment? Prevention?",
    "What do you think about programs like 75 hard?",
    "Is your nutrition the same on the rest days as on workout days?",
    "Just snapped my Achilles, worried about gaining weight! Ideas for exercises and lose weight",
    "What’s your single top tip for running a successful business?",
    "I got generative Disk Disease. Will I be able to lift heavy? Docs said no squat or deadlifts",
    "Your definition of a dirty bulk. Should people bulk up before getting trim?",
    "Is it bad to “chug” your protein shake vs drinking it slowly?",
    "How do you get rid of water retention?",
    "Thoughts on avocado",
    "Whey protein vs egg white powdered protein",
    "What to do if you feel the biceps or triceps contract more on one side than the other during exercise?",
    "What course would you say someone does to learn to be a fitness instructor?",
    "Should you change your training routine when cutting? Weight/reps etc",
    "DB bench press with feet on bench any good?",
    "I notice you like push pull legs split. Is there something wrong with the typical bro split?",
    "Scale has been up the last 10 days, calories have been low like half usual, should I eat less?",
    "What do you think about low carb diet to lose weight",
    "What split do you recommend for 4 days straight/3 off due to work/family?",
    "Are 6 day workout programs necessary for putting on lean mass in a bulk phase?",
    "Would you recommend some lifting weights daily or to have a few rest days?",
    "Top 3 tips for training delts?",
    "What reps/sets do you do to build muscle?",
    "How you eat and workout on vacation, do you track your food?",
    "Importance of nutrition",
    "Supplements",
    "How much protein should I eat while cutting and bulking?",
    "Can eating bread every day make you gain weight?",
    "Can a healthy diet and structured workout program help reduce snoring?",
    "You said don't use protein, but you use protein powder?",
    "Views on haribos gummy bear 80 grams as post workout during lean bulk (clean bulk)",
    "What apart from weight loss can happen to your body when you don't consume all daily calories etc.",
    "Thought on nootropics for better focus and productivity and general crushing life",
    "What should the macros be for body recomp? (deficit maintenance/surplus)",
    "Your favorite podcast?"
      
  ];

  export default questions;